### ISSUE TITLE
Add query paging and pagesize parameters to url

### ISSUE THREAD

**Issue by marcofranssen** [chaoss/grimoirelab-hatstall#112]
To be able to work more efficiently in hatstall it would be very beneficial to have the following reflected in the url.

- page
- pagesize
- query

This would allow to share a page with search results with others, but also to navigate back and forward from the browser.

e.g. http://localhost/identities/hatstall/list?page=5&page_size=50&q=marco

**Comment by MohitPatni0731** [comment]
Can I work on this issue.

**Comment by marcofranssen** [comment]
@valeriocos

**Comment by sduenas** [comment]
Hatstall will be replaced by the Sortinghat UI interface we're working on. That interface already includes the parameters metioned here.

**Comment by marcofranssen** [comment]
Where can we find this new sortinghat-ui? @sduenas

**Comment by sduenas** [comment]
Check `muggle` branch in https://github.com/chaoss/grimoirelab-sortinghat repository. There's no documentation of how to use it yet, though. You will need to install the dependencies with pip, create a database on mysql, apply the django migrations, and run django using `manage.py runserver --settings=config.settings.devel` - you would need to change the credentials of that file.

To run the web interface, go to the directory `ui` and run `yarn serve`.

I'll try to improve the documentation and the installation the last week of January.

**Comment by marcofranssen** [comment]
@sduenas would be great to have a docker container that performs the migration. Then existing users only have to swap the container.

**Comment by sduenas** [comment]
Yes, that's our idea but the problem is the schema of the database will change too, so we need some migration tools from one schema to another.
