### ISSUE TITLE
Cannot access web UI when running hatstall via docker-compose

### ISSUE THREAD

**Issue by sventiffe** [chaoss/grimoirelab-hatstall#116]
I'm evaluating GrimoireLab and followed the instructions to setup a service using docker-compose (see https://github.com/chaoss/grimoirelab/issues/412).

When I open localhost:8000, i can login using the admin default credentials. http://localhost:8000/identities/hatstall/list however will result in HTTP 500. If I follow a deep link from the GrimoireLab Dashboard, e.g. http://127.0.0.1:5601/identities/hatstall/<uuid> then I receive {"statusCode":404,"error":"Not Found","message":"Not Found"}.

Any pointers how to investigate this would be appreciated. I've tried to find logs in the container that help me understanding the issue but did not mange to find them.

**Comment by sduenas** [comment]
Can you paste here your docker compose? Are you using the current image that is on docker hub?

**Comment by sventiffe** [comment]
I've followed [these instructions](https://github.com/chaoss/grimoirelab/tree/master/docker-compose) so I assume the file you are referring to is https://github.com/chaoss/grimoirelab/blob/master/docker-compose/docker-compose.yml

**Comment by sduenas** [comment]
Thanks. As I thought you're using the official image. This image has an error that we're fixing. It's installing a module that requires Python 3.6 but the image only runs Python 3.5.

**Comment by sventiffe** [comment]
I'm new to Docker. Will I be able to apply the fix to the container that I am already running?

**Comment by sduenas** [comment]
Yes, you won't have problems.

**Comment by sventiffe** [comment]
Thanks, I'll wait for the update

**Comment by sventiffe** [comment]
I still experience the issue. I've pulled the changes from chaoss/grimoirelab and restarted my containers. Is there anything else I need or can do in order to access the web UI?

**Comment by sventiffe** [comment]
Fwiw, Hatstall is accessible through http://127.0.0.1:8000/ -- just the deep links from the Dashboard through http://127.0.0.1:5601/identities/hatstall/... do not work

**Comment by zhquan** [comment]
Hi @sventiffe 

Sorry for the late reply. if the URL http://127.0.0.1:8000/ works it means that Hatstall is working well.
If you want to work with http://127.0.0.1:5601/identities/hatstall/ you have to redirect it.

I hope it helps you.

Best,
Quan
