### ISSUE TITLE
Hatstall returns error 500 when uuid is not found

### ISSUE THREAD

**Issue by sanacl** [chaoss/grimoirelab-hatstall#67]
The 500 error is found when Hatstall is not able to find the unified identity. First things first, why a 500 error?

Steps to reproduce it:
* look for someone using Hatstall
* click on the identity
* replace a single character in the url of the uuid and reload

For Bitergia production services take into account that we are changing the status of the identities often. For example when we reset the identities before loading the affiliations file and executing the SortingHat merge. This involves we could have error 500 in several scenarios. Let's see two of them:

Scenario A:
* t0: user keeps the URL of a known Hatstall id in her bookmarks
* t1: someone merge the identity (either person or bot)
* t2: user goes to known id (maybe saved days ago) and gets a 500 error

Scenario B:
* t0: SH breaks all the identities (via reset)
* t1: user goes to Hastall and loads the page for an identity
* t2: SH finishes executes and finish the merge
* t3: user reloads the page and gets a 500 error

**Comment by dlumbrer** [comment]
The issue appears when the uid does not exist in the database, the right behavior is to redirect the user to the "main" page showing an error like "The identity xxxx does not exist" for example.

**Comment by dlumbrer** [comment]
I submitted the #72 PR in order to fix this issue, this is an example of the feature:

![screenshot from 2019-01-02 12-09-43](https://user-images.githubusercontent.com/9249232/50589531-502cd500-0e87-11e9-8bfc-3143974a44b7.png)


Please, check it and test it!
