### ISSUE TITLE
Hatstall does not allow to add/rm/modify domains for organizations

### ISSUE THREAD

**Issue by sanacl** [chaoss/grimoirelab-hatstall#68]
Hatstall offers the possibility to add a new organization but it lacks information such as the domain name. Without that information it is not possible to make the most out the Sortinhat features such as the unify method.

**Comment by jsmanrique** [comment]
Some latest PRs in SortingHat should made this possible if someone wants to work in the UI:
chaoss/grimoirelab-sortinghat#216
chaoss/grimoirelab-sortinghat#217

It should be an easy task for someone with basic Django experience ;-)

**Comment by mafesan** [comment]
I have submitted the following PR which is now ready for review: https://github.com/chaoss/grimoirelab-hatstall/pull/94. Thanks!
