### ISSUE TITLE
Cannot search for user names with less than 3 characters

### ISSUE THREAD

**Issue by aklapper** [chaoss/grimoirelab-hatstall#69]
In Hatstall, if I search for a username with less than three characters (for example a Chinese name which consists of only two letters, which I'd not call uncommon), Hatstall does not allow this: "Please lengthen this text to 3 characters or more".

**Comment by dlumbrer** [comment]
Hi @aklapper 

In order to fix this, I'm going to decrease the minimum length of the search input to 2.

Thanks

**Comment by sduenas** [comment]
This was already done. Closing it.
