### ISSUE TITLE
Do not automatically redirect to frontpage after merging accounts

### ISSUE THREAD

**Issue by aklapper** [chaoss/grimoirelab-hatstall#71]
Directly related to https://github.com/chaoss/grimoirelab-hatstall/issues/70 :

In Hatstall, after merging accounts, Hatstall automatically redirects me to the search page / front page again. 
That means that I have to search for a second time for the (now merged) account in case I want to perform more edits on its account data.

**Comment by dlumbrer** [comment]
Hi @aklapper,

To fix that, I'm going to change the redirection to the identity who will have all the ones merged. Moreover, in that profile, you are able to merge more profiles to it clicking on the "Add" button in the "Profiles Identities" title.

thanks!

**Comment by sduenas** [comment]
Closed by #75
