### ISSUE TITLE
Error 500 updating affiliation date

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-hatstall#86]
I am trying to update Georg affiliation to `University of Nebraska Omaha` in a [demo deployment](http://134.209.60.31:8000/identities/hatstall/a10255c98fb47ccf71cd12cbccc3d7e4bca23a12/).

I can add the organization, but if I try to update the end date, I get an `Error 500 (Server error)` screen.

What can I do?

**Comment by dlumbrer** [comment]
> I am trying to update Georg affiliation to `University of Nebraska Omaha` in a [demo deployment](http://134.209.60.31:8000/identities/hatstall/a10255c98fb47ccf71cd12cbccc3d7e4bca23a12/).
> 
> I can add the organization, but if I try to update the end date, I get an `Error 500 (Server error)` screen.
> 
> What can I do?

We would need information about the logs of the server-side in order to see which part of the application is giving that error.

**Comment by jsmanrique** [comment]
Thank you @dlumbrer. How could I get and provide logs?

**Comment by dlumbrer** [comment]
> Thank you @dlumbrer. How could I get and provide logs?

If you have access to the server and this hatstall is deployed by docker, the docker container should show all the information about it. If not, could you give me more information about where is that hatstall deployed? In order to access the logs with the ops team.

CC @zhquan @sanacl

**Comment by jsmanrique** [comment]
What's the docker command for that?

**Comment by dlumbrer** [comment]
> What's the docker command for that?

`docker <container_name> logs` or `docker-compose -f <compose_file> logs` in case you are using docker compose

**Comment by jsmanrique** [comment]
It seems the command is `docker logs <container_name>` ;-)

```
# docker logs analytics-demo_hatstall_1
Running Hatstall
Cloning into 'grimoirelab-hatstall'...
Site 000-default disabled.
To activate the new configuration, you need to run:
  service apache2 reload
Enabling site apache-hatstall.
To activate the new configuration, you need to run:
  service apache2 reload
Considering dependency setenvif for ssl:
Module setenvif already enabled
Considering dependency mime for ssl:
Module mime already enabled
Considering dependency socache_shmcb for ssl:
Enabling module socache_shmcb.
Enabling module ssl.
See /usr/share/doc/apache2/README.Debian.gz on how to configure SSL and create self-signed certificates.
To activate the new configuration, you need to run:
  service apache2 restart
Django configured for deployment (secret, debug, allowed_hosts) in django_hatstall/settings.py
No changes detected
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying sessions.0001_initial... OK

150 static files copied to '/home/grimoirelab/grimoirelab-hatstall/django-hatstall/static'.
User for django admin created: admin/admin as login
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.6. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.6. Set the 'ServerName' directive globally to suppress this message
[Thu Aug 15 09:49:13.867337 2019] [mpm_event:notice] [pid 80:tid 140662463747264] AH00489: Apache/2.4.25 (Debian) OpenSSL/1.0.2q mod_wsgi/4.5.11 Python/3.5 configured -- resuming normal operations
[Thu Aug 15 09:49:13.867491 2019] [core:notice] [pid 80:tid 140662463747264] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
Running Hatstall
fatal: destination path 'grimoirelab-hatstall' already exists and is not an empty directory.
cp: cannot create regular file 'grimoirelab-hatstall/django-hatstall/shdb.cfg': Permission denied
Site 000-default already disabled
Site apache-hatstall already enabled
Considering dependency setenvif for ssl:
Module setenvif already enabled
Considering dependency mime for ssl:
Module mime already enabled
Considering dependency socache_shmcb for ssl:
Module socache_shmcb already enabled
Module ssl already enabled
sed: couldn't open temporary file /home/grimoirelab/grimoirelab-hatstall/django-hatstall/django_hatstall/sedpUv9TS: Permission denied
Traceback (most recent call last):
  File "./config_deployment.py", line 42, in <module>
    with open(settings_file, "w") as f:
PermissionError: [Errno 13] Permission denied: 'django_hatstall/settings.py'
No changes detected
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.

0 static files copied to '/home/grimoirelab/grimoirelab-hatstall/django-hatstall/static', 150 unmodified.
User for django admin already exists, let's update the password
Password for django admin user updated
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.6. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.6. Set the 'ServerName' directive globally to suppress this message
[Sat Aug 17 20:19:30.385673 2019] [core:warn] [pid 55:tid 139866298520768] AH00098: pid file /var/run/apache2/apache2.pid overwritten -- Unclean shutdown of previous Apache run?
[Sat Aug 17 20:19:30.388647 2019] [mpm_event:notice] [pid 55:tid 139866298520768] AH00489: Apache/2.4.25 (Debian) OpenSSL/1.0.2q mod_wsgi/4.5.11 Python/3.5 configured -- resuming normal operations
[Sat Aug 17 20:19:30.388814 2019] [core:notice] [pid 55:tid 139866298520768] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
```

**Comment by dlumbrer** [comment]
> It seems the command is `docker logs <container_name>` ;-)

Sorry, I was thinking of it right but I wrote it wrong :sweat: 

> 
> ```
> # docker logs analytics-demo_hatstall_1
> Running Hatstall
> Cloning into 'grimoirelab-hatstall'...
> Site 000-default disabled.
> To activate the new configuration, you need to run:
>   service apache2 reload
> Enabling site apache-hatstall.
> To activate the new configuration, you need to run:
>   service apache2 reload
> Considering dependency setenvif for ssl:
> Module setenvif already enabled
> Considering dependency mime for ssl:
> Module mime already enabled
> Considering dependency socache_shmcb for ssl:
> Enabling module socache_shmcb.
> Enabling module ssl.
> See /usr/share/doc/apache2/README.Debian.gz on how to configure SSL and create self-signed certificates.
> To activate the new configuration, you need to run:
>   service apache2 restart
> Django configured for deployment (secret, debug, allowed_hosts) in django_hatstall/settings.py
> No changes detected
> Operations to perform:
>   Apply all migrations: admin, auth, contenttypes, sessions
> Running migrations:
>   Applying contenttypes.0001_initial... OK
>   Applying auth.0001_initial... OK
>   Applying admin.0001_initial... OK
>   Applying admin.0002_logentry_remove_auto_add... OK
>   Applying admin.0003_logentry_add_action_flag_choices... OK
>   Applying contenttypes.0002_remove_content_type_name... OK
>   Applying auth.0002_alter_permission_name_max_length... OK
>   Applying auth.0003_alter_user_email_max_length... OK
>   Applying auth.0004_alter_user_username_opts... OK
>   Applying auth.0005_alter_user_last_login_null... OK
>   Applying auth.0006_require_contenttypes_0002... OK
>   Applying auth.0007_alter_validators_add_error_messages... OK
>   Applying auth.0008_alter_user_username_max_length... OK
>   Applying auth.0009_alter_user_last_name_max_length... OK
>   Applying sessions.0001_initial... OK
> 
> 150 static files copied to '/home/grimoirelab/grimoirelab-hatstall/django-hatstall/static'.
> User for django admin created: admin/admin as login
> AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.6. Set the 'ServerName' directive globally to suppress this message
> AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.6. Set the 'ServerName' directive globally to suppress this message
> [Thu Aug 15 09:49:13.867337 2019] [mpm_event:notice] [pid 80:tid 140662463747264] AH00489: Apache/2.4.25 (Debian) OpenSSL/1.0.2q mod_wsgi/4.5.11 Python/3.5 configured -- resuming normal operations
> [Thu Aug 15 09:49:13.867491 2019] [core:notice] [pid 80:tid 140662463747264] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
> Running Hatstall
> fatal: destination path 'grimoirelab-hatstall' already exists and is not an empty directory.
> cp: cannot create regular file 'grimoirelab-hatstall/django-hatstall/shdb.cfg': Permission denied
> Site 000-default already disabled
> Site apache-hatstall already enabled
> Considering dependency setenvif for ssl:
> Module setenvif already enabled
> Considering dependency mime for ssl:
> Module mime already enabled
> Considering dependency socache_shmcb for ssl:
> Module socache_shmcb already enabled
> Module ssl already enabled
> sed: couldn't open temporary file /home/grimoirelab/grimoirelab-hatstall/django-hatstall/django_hatstall/sedpUv9TS: Permission denied
> Traceback (most recent call last):
>   File "./config_deployment.py", line 42, in <module>
>     with open(settings_file, "w") as f:
> PermissionError: [Errno 13] Permission denied: 'django_hatstall/settings.py'
> No changes detected
> Operations to perform:
>   Apply all migrations: admin, auth, contenttypes, sessions
> Running migrations:
>   No migrations to apply.
> 
> 0 static files copied to '/home/grimoirelab/grimoirelab-hatstall/django-hatstall/static', 150 unmodified.
> User for django admin already exists, let's update the password
> Password for django admin user updated
> AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.6. Set the 'ServerName' directive globally to suppress this message
> AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.6. Set the 'ServerName' directive globally to suppress this message
> [Sat Aug 17 20:19:30.385673 2019] [core:warn] [pid 55:tid 139866298520768] AH00098: pid file /var/run/apache2/apache2.pid overwritten -- Unclean shutdown of previous Apache run?
> [Sat Aug 17 20:19:30.388647 2019] [mpm_event:notice] [pid 55:tid 139866298520768] AH00489: Apache/2.4.25 (Debian) OpenSSL/1.0.2q mod_wsgi/4.5.11 Python/3.5 configured -- resuming normal operations
> [Sat Aug 17 20:19:30.388814 2019] [core:notice] [pid 55:tid 139866298520768] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
> ```

Have you raised the 500 error before these logs? Because I don't see nothing special in hatstall. Perhaps it is an NGINX error (IDK), could you give me a hand @zhquan @sanacl ?

**Comment by jsmanrique** [comment]
Thank you, but I am not able to reproduce the error any longer (I deleted the environment where it was happening), so I prefer to close this issue and reopen it or open a new one if it happens again at some point.
