### ISSUE TITLE
Use bootstrap classes for login form

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-hatstall#87]
Current [login form](https://github.com/chaoss/grimoirelab-hatstall/tree/master/django-hatstall/django_hatstall/templates/registration) is based in `table` layout.

Since Bootstrap is part of HatStall, wouldn't it be nice to use it for login form layout for a more appealing look & feel?

**Comment by dlumbrer** [comment]
I submitted a PR (#88)  that should improve the current login, this is the proposed style:

![Screenshot from 2019-10-21 17-14-41](https://user-images.githubusercontent.com/9249232/67218296-71ff4480-f426-11e9-9838-57adbb09c160.png)


Please @sduenas @valeriocos @jsmanrique test it when you have time, thanks!

**Comment by jsmanrique** [comment]
ILGTM

**Comment by mafesan** [comment]
PR https://github.com/chaoss/grimoirelab-hatstall/pull/88 is now merged, so I'm closing this issue.
