### ISSUE TITLE
Hatstall throws 500 errors after moving droplet to new IP

### ISSUE THREAD

**Issue by RCheesley** [chaoss/grimoirelab-hatstall#90]
I shut down and backed up our instance (based on the analytics-demo package) hosted on Digital Ocean, then moved the droplet over to a team account and spun it up.

Connected in via SSH, fired up the container, fixed the Elasticsearch error, and all seemed to be well.

Since it came back up online, Hatstall is throwing a 500 error, and I can't seem to find a) where the logs might be to track down why and b) understand what might be different between instances.  I also haven't had any data imported since we spun it back up, not sure if this is related or not.

**Comment by valeriocos** [comment]
Issue https://github.com/chaoss/grimoirelab-sirmordred/issues/372 has been closed to centralize the discussion in just one place.

**Comment by RCheesley** [comment]
Thanks, I wasn't sure if this was just with hatstall or where to post if it was an issue affecting multiple parts!

**Comment by valeriocos** [comment]
no worries @RCheesley! In any case thank you for your feedback, this helps us to improve the platform.

As general rule when it isn't clear where to open an issue, you can drop it at https://github.com/chaoss/grimoirelab/issues. Then, we will take care of dispatch it.

Thanks!

@sanacl is having a look at it

**Comment by sanacl** [comment]
Hey @RCheesley , I hope I can help u :)

Please paste here the output of the following commands. Take into account the name of your container will be different, you'll have to replace it: 
* `docker exec -it analytics-demo_hatstall_1_de2bd4f655bf sudo tail -n30 /var/log/apache2/error.log`
* `docker logs --tail=30 analytics-demo_hatstall_1_de2bd4f655bf`

Last but not least, make sure your mariadb container is up.

Waiting for your feedback :nerd_face:

**Comment by RCheesley** [comment]
I think there were a couple of issues at play, one being that the instance had hit 100% space utilisation - since clearing up with a prune, restarting the containers, it seems to be working OK now. I'm not entirely sure if this was due to the space running out or some other cause but will keep an eye!
