### ISSUE TITLE
[Feature request] Select all needed in search results

### ISSUE THREAD

**Issue by RCheesley** [chaoss/grimoirelab-hatstall#91]
When identifying potential merges by searching, a 'select all' feature would be super helpful.

![screenshot-157 245 245 139_8000-2019 11 14-13_50_10](https://user-images.githubusercontent.com/2930593/68862754-ebb4e600-06e5-11ea-8726-037bcecdb59a.png)

**Comment by mafesan** [comment]
Hi @RCheesley, this feature is now added to Hatstall. See PR https://github.com/chaoss/grimoirelab-hatstall/pull/95 for more details. Thanks!
